# Generated by Django 4.0.5 on 2022-11-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_colorvariant_sizevariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color_variant',
            field=models.ManyToManyField(to='product.colorvariant'),
        ),
        migrations.AddField(
            model_name='products',
            name='size_variant',
            field=models.ManyToManyField(to='product.sizevariant'),
        ),
    ]
